"use client";

import { useRef } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Printer, Award, Cpu, Clock, CheckCircle2, FileText } from "lucide-react";
import type { AgentMission } from "@/lib/db/schema";

export function ReportClient({ mission }: { mission: AgentMission }) {
  const router = useRouter();
  const reportRef = useRef<HTMLDivElement>(null);
  const meta = (mission.metadata as Record<string, unknown>) || {};
  const report = (meta.report as Record<string, unknown>) || {};

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Mission Report</title>
      <style>
        body { font-family: Inter, sans-serif; color: #1a1a1a; max-width: 900px; margin: 40px auto; padding: 20px; }
        h1 { font-size: 28px; font-weight: 600; margin-bottom: 4px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
        h2 { font-size: 18px; font-weight: 600; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #eee; padding-bottom: 4px; }
        .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 12px 0; }
        .card { background: #f5f5f5; padding: 12px; border-radius: 4px; }
        .card .val { font-size: 24px; font-weight: 700; }
        .card .lab { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.05em; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 13px; }
        th { font-weight: 600; color: #333; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
      </style></head><body>
      <h1>Mission Report</h1>
      <p class="meta">${mission.goal} · ${new Date(mission.createdAt!).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>
      <div class="grid">
        <div class="card"><div class="val">${report.success || mission.status === "complete" ? "100" : "0"}%</div><div class="lab">Success Rate</div></div>
        <div class="card"><div class="val">${mission.currentIteration}</div><div class="lab">Iterations</div></div>
        <div class="card"><div class="val">${report.documentsGenerated || 0}</div><div class="lab">Documents</div></div>
        <div class="card"><div class="val">${report.sourcesFound || 0}</div><div class="lab">Sources</div></div>
      </div>
      <h2>Mission Details</h2>
      <table><tr><th>Status</th><td>${mission.status}</td></tr>
      <tr><th>Goal</th><td>${mission.goal}</td></tr>
      <tr><th>Started</th><td>${new Date(mission.createdAt!).toLocaleString()}</td></tr>
      <tr><th>Last Updated</th><td>${new Date(mission.updatedAt!).toLocaleString()}</td></tr>
      <tr><th>Session ID</th><td style="font-family:monospace;font-size:12px">${mission.sessionId}</td></tr></table>
      <p class="footer">Generated by Opportunity AI · Gemma 4 Autonomous Agent</p>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="min-h-screen bg-[#0B0E13] text-[#F3EEE1]" style={{ fontFamily: "var(--font-body)" }}>
      <div className="mx-auto max-w-4xl px-4 py-8">
        <div className="flex items-center justify-between mb-8">
          <button onClick={() => router.back()} className="flex items-center gap-1.5 text-[13px] text-[#F3EEE1]/50 hover:text-[#F3EEE1] transition-colors">
            <ArrowLeft className="h-4 w-4" /> Back
          </button>
          <div className="flex items-center gap-2">
            <button onClick={handlePrint} className="flex items-center gap-1.5 rounded-sm border border-[#F3EEE1]/15 px-3.5 py-2 text-[12px] font-medium text-[#F3EEE1]/60 hover:text-[#F3EEE1] hover:bg-[#F3EEE1]/[0.03] transition-all">
              <Printer className="h-3.5 w-3.5" /> Print / PDF
            </button>
            <button onClick={() => router.push(`/dashboard/${mission.sessionId}`)} className="flex items-center gap-1.5 rounded-sm bg-[#C9A227] px-3.5 py-2 text-[12px] font-semibold text-[#0B0E13] hover:-translate-y-0.5 transition-all">
              <ArrowLeft className="h-3.5 w-3.5" /> Dashboard
            </button>
          </div>
        </div>

        <div ref={reportRef} className="rounded-sm border border-[#F3EEE1]/10 bg-[#12161D] p-8">
          <div className="flex items-center gap-3 mb-1">
            <div className="flex h-10 w-10 items-center justify-center rounded-sm border border-[#C9A227]/30 bg-[#C9A227]/10">
              <Award className="h-5 w-5 text-[#C9A227]" strokeWidth={1.75} />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight" style={{ fontFamily: "var(--font-display)" }}>Mission Report</h1>
              <p className="text-sm text-[#F3EEE1]/40">{new Date(mission.createdAt!).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>
            </div>
          </div>

          <div className="mt-6 mb-8">
            <p className="text-lg font-medium text-[#F3EEE1] mb-1" style={{ fontFamily: "var(--font-display)" }}>{mission.goal}</p>
            <div className="flex items-center gap-3 font-mono text-[12px] text-[#F3EEE1]/40">
              <span className={`inline-flex items-center gap-1 rounded-sm px-2 py-0.5 ${
                mission.status === "complete" ? "bg-[#3FA78E]/10 text-[#3FA78E] border border-[#3FA78E]/20" :
                mission.status === "running" ? "bg-[#C9A227]/10 text-[#C9A227] border border-[#C9A227]/20" :
                "bg-[#C2703D]/10 text-[#C2703D] border border-[#C2703D]/20"
              }`}>
                {mission.status.toUpperCase()}
              </span>
              <span>ID: <span className="text-[#F3EEE1]/60">{mission.sessionId.slice(0, 8)}</span></span>
              <span>{mission.currentIteration} iteration{mission.currentIteration !== 1 ? "s" : ""}</span>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
            {[
              { label: "Success", value: `${report.success || (mission.status === "complete" ? 100 : 0)}%`, icon: CheckCircle2, color: "text-[#3FA78E]" },
              { label: "Iterations", value: `${mission.currentIteration}`, icon: Cpu, color: "text-[#C9A227]" },
              { label: "Documents", value: `${report.documentsGenerated || 0}`, icon: FileText, color: "text-[#F3EEE1]" },
              { label: "Duration", value: report.duration ? `${Math.round(Number(report.duration) / 60)}m` : "—", icon: Clock, color: "text-[#F3EEE1]/50" },
            ].map(s => (
              <div key={s.label} className="rounded-sm border border-[#F3EEE1]/[0.06] bg-[#0B0E13]/50 px-4 py-3">
                <div className="flex items-center gap-1.5 mb-1">
                  <s.icon className="h-3.5 w-3.5" strokeWidth={1.75} />
                  <span className="font-mono text-[11px] text-[#F3EEE1]/40">{s.label}</span>
                </div>
                <p className={`text-xl font-bold font-mono ${s.color}`}>{s.value}</p>
              </div>
            ))}
          </div>

          <div className="space-y-4">
            <h2 className="text-sm font-semibold text-[#F3EEE1] border-b border-[#F3EEE1]/10 pb-2" style={{ fontFamily: "var(--font-display)" }}>Mission Details</h2>
            <div className="grid grid-cols-2 gap-x-6 gap-y-3 text-[13px]">
              {[
                ["Status", mission.status.toUpperCase()],
                ["Goal", mission.goal],
                ["Started", new Date(mission.createdAt!).toLocaleString()],
                ["Last Updated", new Date(mission.updatedAt!).toLocaleString()],
                ["Session ID", mission.sessionId.slice(0, 8) + "..."],
                ["Iterations", `${mission.currentIteration}/6`],
              ].map(([label, value]) => (
                <div key={label} className="flex justify-between gap-4">
                  <span className="text-[#F3EEE1]/40 font-mono text-[11px] uppercase tracking-wider">{label}</span>
                  <span className="text-[#F3EEE1]/70 text-right truncate">{value}</span>
                </div>
              ))}
            </div>
          </div>

          {(report.recommendation as string) && (
            <div className="mt-6 rounded-sm border border-[#C9A227]/20 bg-[#C9A227]/[0.04] px-4 py-3">
              <p className="font-mono text-[11px] text-[#C9A227]/60 uppercase tracking-wider mb-1">AI Recommendation</p>
              <p className="text-sm text-[#C9A227]/80 leading-relaxed">{String(report.recommendation)}</p>
            </div>
          )}

          <div className="mt-8 pt-4 border-t border-[#F3EEE1]/10">
            <p className="text-[12px] text-[#F3EEE1]/25 font-mono text-center">
              Generated by Opportunity AI · Powered by Google Gemma 4
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
