import "dotenv/config";
import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL!);

const seedData = [
  // === SCHOLARSHIPS (10) ===
  {
    title: "Mastercard Foundation Scholars Program",
    slug: "mastercard-foundation-scholars",
    type: "scholarship",
    provider: "Mastercard Foundation",
    description: "Comprehensive scholarship for African students to pursue degrees at partner universities worldwide. Covers full tuition, accommodation, living expenses, and leadership development.",
    eligibility_criteria: "African citizen or refugee. Academic excellence. Leadership potential. Commitment to community. Financial need.",
    benefits: "Full tuition, accommodation, living stipend, travel, laptop, health insurance, leadership program",
    application_url: "https://mastercardfoundation.org/scholars",
    deadline: "2026-09-30",
    location: "Various",
    isRemote: false,
    target_audience: ["undergraduate", "graduate"],
    required_skills: ["leadership", "academic excellence"],
    preferred_skills: ["community service", "problem-solving"],
    experience_level: "entry",
    tags: ["scholarship", "full-funding", "undergraduate", "graduate", "leadership", "Africa"],
  },
  {
    title: "AWS AI & ML Scholarship",
    slug: "aws-ai-ml-scholarship",
    type: "scholarship",
    provider: "Amazon Web Services",
    description: "AI and machine learning education scholarship. Includes Udacity nanodegree, AWS credits, and mentorship. No prior ML experience required.",
    eligibility_criteria: "Students aged 16+. Demonstrated interest in AI/ML. Must complete foundational AI course.",
    benefits: "Udacity nanodegree, AWS credits, mentorship, certification preparation",
    application_url: "https://aws.amazon.com/machine-learning/scholarship",
    deadline: "2026-05-01",
    location: "Remote",
    isRemote: true,
    target_audience: ["high_school", "undergraduate"],
    required_skills: ["basic programming", "interest in AI"],
    preferred_skills: ["Python", "mathematics"],
    experience_level: "entry",
    tags: ["scholarship", "AI", "machine-learning", "beginner-friendly", "remote"],
  },
  {
    title: "Vanier Canada Graduate Scholarship (AI)",
    slug: "vanier-canada-ai-scholarship",
    type: "scholarship",
    provider: "Government of Canada",
    description: "Prestigious $50,000/year scholarship for PhD students in AI and related fields at Canadian universities. Open to international students including Nigerians.",
    eligibility_criteria: "First-class average in previous degrees. Research excellence in AI/CS. Strong recommendation letters. Leadership qualities.",
    benefits: "$50,000 CAD yearly for 3 years, research funding, networking events",
    application_url: "https://vanier.gc.ca",
    deadline: "2026-09-15",
    location: "Canada",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["research", "AI", "academic excellence"],
    preferred_skills: ["machine learning", "publications", "leadership"],
    experience_level: "mid",
    tags: ["scholarship", "Canada", "PhD", "AI", "research", "international"],
  },
  {
    title: "DAAD Scholarship for AI in Germany",
    slug: "daad-ai-germany",
    type: "scholarship",
    provider: "DAAD",
    description: "Fully-funded master's and PhD scholarships for developing country students to study AI, CS, and related fields at German universities.",
    eligibility_criteria: "Bachelor's degree with strong grades. From developing country (including Nigeria). German language not required for English programs.",
    benefits: "€992/month stipend, health insurance, travel allowance, tuition-free education",
    application_url: "https://daad.de/en/study-and-research-in-germany/scholarships",
    deadline: "2026-07-31",
    location: "Germany",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["academic excellence"],
    preferred_skills: ["German language", "research experience"],
    experience_level: "entry",
    tags: ["scholarship", "Germany", "AI", "full-funding", "international"],
  },
  {
    title: "Chevening Scholarship UK",
    slug: "chevening-uk",
    type: "scholarship",
    provider: "UK Foreign & Commonwealth Office",
    description: "Full UK government scholarship for one-year master's degree at any UK university. Leadership-focused program with global network.",
    eligibility_criteria: "Citizen of Chevening-eligible country (Nigeria included). Minimum 2 years work experience. Strong academic background. Leadership potential.",
    benefits: "Full tuition, living stipend, travel, visa fees, networking, exclusive events",
    application_url: "https://chevening.org",
    deadline: "2026-11-01",
    location: "United Kingdom",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["leadership", "academic excellence", "work experience"],
    preferred_skills: ["networking", "communication"],
    experience_level: "mid",
    tags: ["scholarship", "UK", "full-funding", "leadership", "master"],
  },
  {
    title: "Erasmus Mundus Joint Masters in AI",
    slug: "erasmus-mundus-ai",
    type: "scholarship",
    provider: "European Union",
    description: "Full scholarship for 2-year joint European master's in Artificial Intelligence across multiple EU universities. Includes travel and living costs.",
    eligibility_criteria: "Bachelor's degree in CS or related field. Strong academic record. English proficiency.",
    benefits: "Full tuition, €1,400/month living stipend, travel, insurance, installation costs",
    application_url: "https://erasmus-plus.ec.europa.eu",
    deadline: "2026-02-15",
    location: "Europe",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["computer science", "programming", "mathematics"],
    preferred_skills: ["machine learning", "Python", "research"],
    experience_level: "entry",
    tags: ["scholarship", "Europe", "AI", "full-funding", "master", "Erasmus"],
  },
  {
    title: "TTUF Scholarship for African Women in Tech",
    slug: "ttuf-women-tech",
    type: "scholarship",
    provider: "The Tonye Trust Foundation",
    description: "Full scholarship for African women pursuing undergraduate/graduate degrees in technology fields including AI and data science.",
    eligibility_criteria: "Female African student. Accepted into accredited tech program. Demonstrated financial need. Community involvement.",
    benefits: "Full tuition, laptop, mentorship, internship placement, leadership training",
    application_url: "https://tonyetrust.org",
    deadline: "2026-08-01",
    location: "Various",
    isRemote: false,
    target_audience: ["undergraduate", "graduate"],
    required_skills: ["academic excellence"],
    preferred_skills: ["technology", "community service"],
    experience_level: "entry",
    tags: ["scholarship", "women", "Africa", "technology", "full-funding"],
  },
  {
    title: "Chinese Government Scholarship in AI",
    slug: "china-scholarship-ai",
    type: "scholarship",
    provider: "Chinese Scholarship Council",
    description: "Full scholarship for African students to pursue AI/CS degrees at top Chinese universities including Tsinghua and Peking.",
    eligibility_criteria: "Under 35 (master's) or 40 (PhD). Good health. Strong academic background. English or Chinese proficiency.",
    benefits: "Full tuition, accommodation, monthly stipend, comprehensive medical insurance",
    application_url: "https://campuschina.org",
    deadline: "2026-04-30",
    location: "China",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["academic excellence"],
    preferred_skills: ["Chinese language", "research"],
    experience_level: "entry",
    tags: ["scholarship", "China", "AI", "full-funding", "international"],
  },
  {
    title: "MEXT Scholarship for AI in Japan",
    slug: "mext-japan-ai",
    type: "scholarship",
    provider: "Japanese Government (MEXT)",
    description: "Full Japanese government scholarship for AI/CS research students at top Japanese universities. Includes language training.",
    eligibility_criteria: "Under 35. Bachelor's degree. GPA 3.0+. Japanese or English proficiency.",
    benefits: "Full tuition, ¥143,000-145,000/month stipend, travel, accommodation support",
    application_url: "https://mext.go.jp",
    deadline: "2026-05-15",
    location: "Japan",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["research", "academic excellence"],
    preferred_skills: ["Japanese language", "AI", "programming"],
    experience_level: "entry",
    tags: ["scholarship", "Japan", "AI", "full-funding", "research"],
  },
  {
    title: "Schwarzman Scholars Program for AI Policy",
    slug: "schwarzman-ai-policy",
    type: "scholarship",
    provider: "Schwarzman Scholars",
    description: "One-year fully-funded master's in global affairs with AI policy focus at Tsinghua University, Beijing. Leadership and networking focus.",
    eligibility_criteria: "Aged 18-28. Bachelor's degree. English proficiency. Leadership potential. Interest in US-China relations.",
    benefits: "Full tuition, room and board, travel, laptop, personal stipend, leadership program",
    application_url: "https://schwarzmanscholars.org",
    deadline: "2026-09-15",
    location: "China",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["leadership", "academic excellence", "English"],
    preferred_skills: ["AI interest", "policy", "global affairs"],
    experience_level: "mid",
    tags: ["scholarship", "China", "AI-policy", "leadership", "full-funding"],
  },

  // === FELLOWSHIPS (7) ===
  {
    title: "Google Research Fellowship",
    slug: "google-research-fellowship",
    type: "fellowship",
    provider: "Google",
    description: "Supporting exceptional PhD students in computer science and related fields. Provides funding, mentorship from Google researchers, and networking.",
    eligibility_criteria: "Full-time PhD student. Research in CS, ML, or related field. Strong publication record. University nomination required.",
    benefits: "Tuition and fees, living stipend, research budget, Google mentor, internship opportunities",
    application_url: "https://research.google/fellowships",
    deadline: "2026-03-15",
    location: "Various",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["research", "machine learning", "programming"],
    preferred_skills: ["deep learning", "NLP", "computer vision", "publications"],
    experience_level: "mid",
    tags: ["fellowship", "research", "PhD", "computer-science", "AI"],
  },
  {
    title: "Andela Technical Leadership Program",
    slug: "andela-tech-leadership",
    type: "fellowship",
    provider: "Andela",
    description: "Connects African software developers with global companies. Technical training, leadership development, and placement at partner organizations.",
    eligibility_criteria: "Based in Africa. 2+ years software development experience. Strong technical skills. Excellent communication.",
    benefits: "Paid placement, technical training, leadership development, global network, career coaching",
    application_url: "https://andela.com/fellowship",
    deadline: "2026-08-01",
    location: "Remote",
    isRemote: true,
    target_audience: ["professional"],
    required_skills: ["software development", "JavaScript", "Python", "communication"],
    preferred_skills: ["React", "Node.js", "cloud computing", "system design"],
    experience_level: "mid",
    tags: ["fellowship", "software-engineering", "remote", "career-growth", "Africa"],
  },
  {
    title: "DeepMind Academic Fellowship",
    slug: "deepmind-academic-fellowship",
    type: "fellowship",
    provider: "DeepMind",
    description: "Research fellowship for PhD students in AI/ML from underrepresented backgrounds. Funding, compute resources, and DeepMind researcher mentorship.",
    eligibility_criteria: "PhD student in AI/ML. From underrepresented group in AI. Strong research potential. Supervised at accredited university.",
    benefits: "Research funding, Google Cloud credits, DeepMind mentorship, conference travel",
    application_url: "https://deepmind.com/careers/academic-fellowships",
    deadline: "2026-04-01",
    location: "Remote",
    isRemote: true,
    target_audience: ["graduate"],
    required_skills: ["AI", "machine learning", "research"],
    preferred_skills: ["deep learning", "reinforcement learning", "publications"],
    experience_level: "mid",
    tags: ["fellowship", "AI", "PhD", "mentorship", "remote", "diversity"],
  },
  {
    title: "Mozilla Open Source Fellowship",
    slug: "mozilla-open-source-fellowship",
    type: "fellowship",
    provider: "Mozilla",
    description: "For open source contributors advancing internet health. Stipend, mentorship, and community support.",
    eligibility_criteria: "Active open source project or significant contributions. Project must align with Mozilla's mission.",
    benefits: "Stipend, mentorship, community access, conference travel, project funding",
    application_url: "https://foundation.mozilla.org/fellowships",
    deadline: "2026-06-30",
    location: "Remote",
    isRemote: true,
    target_audience: ["undergraduate", "graduate", "professional"],
    required_skills: ["open source", "programming"],
    preferred_skills: ["web development", "privacy", "security", "community building"],
    experience_level: "any",
    tags: ["fellowship", "open-source", "remote", "technology"],
  },
  {
    title: "Carnegie Mellon AI Research Fellowship",
    slug: "cmu-ai-fellowship",
    type: "fellowship",
    provider: "Carnegie Mellon University",
    description: "Fully-funded PhD fellowship in AI at CMU's world-leading School of Computer Science. Research in ML, NLP, robotics, and computer vision.",
    eligibility_criteria: "Strong academic background in CS/AI. Research experience. GRE scores. English proficiency.",
    benefits: "Full tuition, $40,000+ stipend, health insurance, research funding, conference travel",
    application_url: "https://cs.cmu.edu/admissions",
    deadline: "2026-12-01",
    location: "USA",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["computer science", "research", "programming"],
    preferred_skills: ["machine learning", "mathematics", "publications"],
    experience_level: "mid",
    tags: ["fellowship", "USA", "AI", "PhD", "research", "full-funding"],
  },
  {
    title: "Milele AI Fellowship for African Students",
    slug: "milele-ai-fellowship",
    type: "fellowship",
    provider: "Milele AI Foundation",
    description: "Dedicated AI fellowship for African students pursuing graduate degrees in AI/ML. Includes funding, compute credits, and industry mentorship.",
    eligibility_criteria: "African citizen. Admitted to graduate AI/ML program. Demonstrated commitment to solving African problems with AI.",
    benefits: "$30,000/year stipend, tuition support, AWS credits, mentorship, internship placement",
    application_url: "https://milele.ai/fellowship",
    deadline: "2026-05-30",
    location: "Various",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["AI", "machine learning", "programming"],
    preferred_skills: ["Python", "research", "African development"],
    experience_level: "entry",
    tags: ["fellowship", "AI", "Africa", "graduate", "mentorship"],
  },
  {
    title: "Schmidt Science Fellows",
    slug: "schmidt-science-fellows",
    type: "fellowship",
    provider: "Schmidt Futures",
    description: "Postdoctoral fellowship for early-career scientists including AI researchers. $100,000 stipend + research funding. Must propose interdisciplinary project.",
    eligibility_criteria: "PhD in STEM field completed within 3 years. Proposed interdisciplinary research. Strong recommendations.",
    benefits: "$100,000 stipend, $50,000 research budget, mentorship, community events",
    application_url: "https://schmidtsciencefellows.org",
    deadline: "2026-10-01",
    location: "Various",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["research", "PhD", "STEM"],
    preferred_skills: ["interdisciplinary", "leadership", "communication"],
    experience_level: "senior",
    tags: ["fellowship", "postdoc", "research", "STEM", "funding"],
  },

  // === INTERNSHIPS (5) ===
  {
    title: "Google AI Internship (Canada)",
    slug: "google-ai-internship-canada",
    type: "internship",
    provider: "Google",
    description: "AI/ML research internship at Google offices in Montreal, Toronto, or Waterloo. Work on cutting-edge AI research with Google Brain/DeepMind teams.",
    eligibility_criteria: "Currently pursuing BSc/MSc/PhD in CS/AI. Strong programming skills. ML coursework or research experience.",
    benefits: "Competitive salary, relocation support, housing stipend, mentorship, networking events",
    application_url: "https://careers.google.com/jobs/internships",
    deadline: "2026-10-31",
    location: "Canada",
    isRemote: false,
    target_audience: ["undergraduate", "graduate"],
    required_skills: ["programming", "machine learning", "Python"],
    preferred_skills: ["deep learning", "TensorFlow", "research", "publications"],
    experience_level: "any",
    tags: ["internship", "Canada", "AI", "Google", "research"],
  },
  {
    title: "OpenAI Fellowship Program",
    slug: "openai-fellowship",
    type: "internship",
    provider: "OpenAI",
    description: "6-month residency for early-career AI researchers from underrepresented backgrounds. Work with OpenAI researchers on safe AI development.",
    eligibility_criteria: "Early-career (undergrad/grad). Demonstrated AI interest. From underrepresented group. Python proficiency.",
    benefits: "$10,000/month stipend, housing, travel, compute resources, mentorship",
    application_url: "https://openai.com/careers",
    deadline: "2026-03-01",
    location: "Remote",
    isRemote: true,
    target_audience: ["undergraduate", "graduate"],
    required_skills: ["Python", "machine learning", "AI ethics interest"],
    preferred_skills: ["deep learning", "research", "communication"],
    experience_level: "entry",
    tags: ["internship", "AI", "remote", "research", "diversity"],
  },
  {
    title: "Meta AI Research Internship",
    slug: "meta-ai-internship",
    type: "internship",
    provider: "Meta (Facebook)",
    description: "AI research internship at Meta AI labs worldwide. Work on FAIR (Facebook AI Research) projects in NLP, CV, and RL.",
    eligibility_criteria: "PhD/MSc student in CS/AI. Research experience in AI/ML. Strong publication record preferred.",
    benefits: "Competitive salary, relocation, housing, mentorship, publication opportunities",
    application_url: "https://metacareers.com/jobs/internships",
    deadline: "2026-02-28",
    location: "Various",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["research", "AI", "machine learning", "programming"],
    preferred_skills: ["NLP", "computer vision", "reinforcement learning", "publications"],
    experience_level: "mid",
    tags: ["internship", "AI", "research", "Meta", "international"],
  },
  {
    title: "Microsoft AI Research Internship (Montreal)",
    slug: "microsoft-ai-montreal",
    type: "internship",
    provider: "Microsoft Research",
    description: "AI research internship at Microsoft Research Montreal. Work with world-class AI researchers on deep learning and reinforcement learning.",
    eligibility_criteria: "Enrolled in PhD/MSc in AI/CS. Research experience. Strong publication record.",
    benefits: "Competitive salary, relocation, housing, mentorship, Azure compute access",
    application_url: "https://careers.microsoft.com",
    deadline: "2026-08-31",
    location: "Canada",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["AI research", "deep learning", "programming"],
    preferred_skills: ["reinforcement learning", "NLP", "PyTorch", "publications"],
    experience_level: "mid",
    tags: ["internship", "Canada", "AI", "research", "Microsoft"],
  },
  {
    title: "DeepMind Student Researcher Program",
    slug: "deepmind-student-researcher",
    type: "internship",
    provider: "DeepMind",
    description: "3-6 month student researcher placement at DeepMind London. Contribute to frontier AI research projects with DeepMind scientists.",
    eligibility_criteria: "Currently enrolled PhD/MSc in AI/ML. Strong ML fundamentals. Python proficiency.",
    benefits: "£2,500/month stipend, travel reimbursement, mentorship, lunch, events",
    application_url: "https://deepmind.com/careers/student-researchers",
    deadline: "2026-05-01",
    location: "United Kingdom",
    isRemote: false,
    target_audience: ["graduate"],
    required_skills: ["machine learning", "Python", "research"],
    preferred_skills: ["deep learning", "reinforcement learning", "mathematics"],
    experience_level: "mid",
    tags: ["internship", "UK", "AI", "research", "DeepMind"],
  },

  // === COMPETITIONS (2) ===
  {
    title: "Zindi Data Science Competition",
    slug: "zindi-competition",
    type: "competition",
    provider: "Zindi",
    description: "Africa's largest data science competition platform. Solve real-world African problems using ML. Win prizes and get recognized by employers.",
    eligibility_criteria: "Open to all. Teams of up to 5. Submit predictions in specified format.",
    benefits: "Cash prizes, recognition, job opportunities, portfolio building",
    application_url: "https://zindi.africa",
    deadline: null,
    location: "Remote",
    isRemote: true,
    target_audience: ["undergraduate", "graduate", "professional"],
    required_skills: ["data science", "machine learning", "Python"],
    preferred_skills: ["data visualization", "feature engineering", "deep learning"],
    experience_level: "any",
    tags: ["competition", "data-science", "machine-learning", "Africa", "prizes"],
  },
  {
    title: "Kaggle AI for Africa Competition",
    slug: "kaggle-ai-africa",
    type: "competition",
    provider: "Kaggle",
    description: "Kaggle competition focused on AI solutions for African challenges. $50,000 prize pool. Sponsored by Google AI.",
    eligibility_criteria: "Open to all. Must submit ML model predictions. Teams of 1-5 members.",
    benefits: "Cash prizes, Kaggle medals, recognition, job recruitment opportunities",
    application_url: "https://kaggle.com/competitions",
    deadline: "2026-06-01",
    location: "Remote",
    isRemote: true,
    target_audience: ["undergraduate", "graduate", "professional"],
    required_skills: ["machine learning", "Python", "data analysis"],
    preferred_skills: ["deep learning", "feature engineering", "cloud computing"],
    experience_level: "any",
    tags: ["competition", "AI", "Kaggle", "Africa", "prizes"],
  },

  // === CONFERENCES (2) ===
  {
    title: "Deep Learning Indaba 2026",
    slug: "deep-learning-indaba-2026",
    type: "conference",
    provider: "Deep Learning Indaba",
    description: "Largest AI gathering in Africa. Workshops, tutorials, research presentations. Travel grants available for African students.",
    eligibility_criteria: "Open to all African AI researchers and students. Travel grant requires ML interest and proof of enrollment.",
    benefits: "Conference access, workshops, networking, travel grants, research poster sessions",
    application_url: "https://deeplearningindaba.com",
    deadline: "2026-04-15",
    location: "Senegal",
    isRemote: false,
    target_audience: ["undergraduate", "graduate", "professional"],
    required_skills: ["machine learning", "AI interest"],
    preferred_skills: ["research", "deep learning", "Python"],
    experience_level: "any",
    tags: ["conference", "AI", "machine-learning", "Africa", "networking"],
  },
  {
    title: "NeurIPS 2026",
    slug: "neurips-2026",
    type: "conference",
    provider: "Neural Information Processing Systems Foundation",
    description: "Premier AI/ML conference. Scholarships available for African students covering travel, registration, and accommodation.",
    eligibility_criteria: "Submit paper or demonstrate financial need. Student status. AI/ML research area.",
    benefits: "Travel grant, free registration, accommodation, networking, top AI research",
    application_url: "https://neurips.cc",
    deadline: "2026-05-15",
    location: "Canada",
    isRemote: false,
    target_audience: ["graduate", "professional"],
    required_skills: ["AI research", "machine learning"],
    preferred_skills: ["publications", "deep learning", "programming"],
    experience_level: "mid",
    tags: ["conference", "AI", "research", "Canada", "top-tier"],
  },

  // === GRANTS (2) ===
  {
    title: "ICLR Travel Grant for African Researchers",
    slug: "iclr-travel-grant-africa",
    type: "grant",
    provider: "International Conference on Learning Representations",
    description: "Travel grant for African AI researchers to attend ICLR 2026. Covers flights, accommodation, and registration.",
    eligibility_criteria: "African AI researcher or student. Paper accepted or demonstrated research interest. Financial need.",
    benefits: "Round-trip flights, hotel, conference registration, per diem",
    application_url: "https://iclr.cc",
    deadline: "2026-02-01",
    location: "Various",
    isRemote: false,
    target_audience: ["graduate", "professional"],
    required_skills: ["AI research"],
    preferred_skills: ["publications", "deep learning"],
    experience_level: "any",
    tags: ["grant", "conference", "travel", "Africa", "AI"],
  },
  {
    title: "Google AI Research Grant for Africa",
    slug: "google-ai-grant-africa",
    type: "grant",
    provider: "Google AI",
    description: "Research grants up to $50,000 for African researchers working on AI solutions to local challenges. Compute credits included.",
    eligibility_criteria: "African institution affiliation. AI research addressing African challenges. Clear methodology and timeline.",
    benefits: "Up to $50,000 research funding, Google Cloud credits, Google researcher mentorship",
    application_url: "https://ai.google/research/programs",
    deadline: "2026-07-15",
    location: "Africa",
    isRemote: false,
    target_audience: ["graduate", "professional"],
    required_skills: ["AI research", "research methodology"],
    preferred_skills: ["machine learning", "African development", "Python"],
    experience_level: "mid",
    tags: ["grant", "AI", "Africa", "research", "funding", "Google"],
  },

  // === RESEARCH (1) ===
  {
    title: "Vector Institute AI Research Grant",
    slug: "vector-ai-research-grant",
    type: "research",
    provider: "Vector Institute",
    description: "Research grant for AI projects at the Vector Institute, Toronto. Access to compute, data, and world-class AI researchers.",
    eligibility_criteria: "Affiliated with Vector Institute or partner university. AI/ML research focus. Demonstrated research capability.",
    benefits: "Research funding, compute resources, collaboration, publication support",
    application_url: "https://vectorinstitute.ai/research",
    deadline: "2026-03-31",
    location: "Canada",
    isRemote: false,
    target_audience: ["graduate", "professional"],
    required_skills: ["AI research", "machine learning"],
    preferred_skills: ["deep learning", "NLP", "computer vision"],
    experience_level: "mid",
    tags: ["research", "AI", "Canada", "grant", "Vector"],
  },
];

async function main() {
  console.log(`Seeding ${seedData.length} opportunities...\n`);
  let inserted = 0;
  for (const opp of seedData) {
    const exists = await sql`SELECT id FROM opportunities WHERE slug = ${opp.slug}`;
    if (exists.length > 0) {
      console.log(`  ~ ${opp.title} already exists, skipping`);
      continue;
    }
    await sql`
      INSERT INTO opportunities (title, slug, type, provider, description, eligibility_criteria, benefits, application_url, deadline, location, is_remote, target_audience, required_skills, preferred_skills, experience_level, tags)
      VALUES (${opp.title}, ${opp.slug}, ${opp.type}, ${opp.provider}, ${opp.description}, ${opp.eligibility_criteria}, ${opp.benefits}, ${opp.application_url}, ${opp.deadline}, ${opp.location}, ${opp.isRemote}, ${opp.target_audience}, ${opp.required_skills}, ${opp.preferred_skills}, ${opp.experience_level}, ${opp.tags})
    `;
    console.log(`  \u2713 ${opp.title}`);
    inserted++;
  }
  console.log(`\nDone. ${inserted} new opportunities inserted.`);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
